version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: anthonybauld-aggr-trade_web_1
      APP_PORT: 80

  web:
    image: anthonybauld-aggr-trade:3.8.3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AGGR_REF: 6c1d85d2802bddb7a32545548de7b56aeaf9e1f7
    restart: on-failure
    stop_grace_period: 1m
