services:
  app_proxy:
    environment:
      APP_HOST: anthonybauld-aggr-trade_web_1
      APP_PORT: 80

  web:
    image: ghcr.io/anthonybauld/anthonybauld-aggr-trade:3.8.3
    restart: on-failure
    stop_grace_period: 1m
