services:
  app_proxy:
    environment:
      APP_HOST: anthonybauld-aggr-trade_app_1
      APP_PORT: 8080

  app:
    image: ghcr.io/anthonybauld/anthonybauld-aggr-trade:3.8.3-umbrel1
    restart: unless-stopped
