services:
  app_proxy:
    environment:
      APP_HOST: anthonybauld-aggr-trade_app_1
      APP_PORT: 80

  app:
    image: ghcr.io/anthonybauld/anthonybauld-aggr-trade@sha256:6f15de3cd2b5dc026551c34841fa297e9e05dc652c262f3262a1dc859ded513a
    restart: unless-stopped
