version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: aggr-trade_web_1
      APP_PORT: 80

  web:
    image: aggr-trade:3.8.3
    build:
      context: ../../aggr
      dockerfile: docker/Dockerfile
    restart: on-failure
    stop_grace_period: 1m
